services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/live-chat
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://admin:admin123@rabbitmq:5672
      - JWT_SECRET=Gm82f93D@ksl!38NF29fJdkSL82nfs
      - JWT_REFRESH_SECRET=SdK29f!FJ83kdLz29DjF8dKsl3Fj
    depends_on:
      - mongo
      - redis
      - rabbitmq
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - live-chat-network

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=live-chat
    volumes:
      - mongo_data:/data/db
    networks:
      - live-chat-network

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - live-chat-network

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    ports:
      - "8080:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - live-chat-network

volumes:
  mongo_data:
  redis_data:
  rabbitmq_data:

networks:
  live-chat-network:
    driver: bridge 