services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://mongo:27017/live-chat
      - REDIS_URL=redis://redis:6379
      - RABBITMQ_URL=amqp://admin:admin123@localhost:5672
      - JWT_SECRET=Gm82f93D@ksl!38NF29fJdkSL82nfs
      - JWT_REFRESH_SECRET=SdK29f!FJ83kdLz29DjF8dKsl3Fj
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - live-chat-network

  mongo:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=live-chat
    volumes:
      - mongo_data:/data/db
    networks:
      - live-chat-network

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - live-chat-network

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    configs:
      - source: rabbitmq-plugins
        target: /etc/rabbitmq/enabled_plugins
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq
    networks:
      - live-chat-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

configs:
  rabbitmq-plugins:
    content: "[rabbitmq_management]."  

volumes:
  mongo_data:
  redis_data:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local

networks:
  live-chat-network:
    driver: bridge 

